# Name of this workflow
name: Regression Test

# Trigger Event
# ref: https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows
on: [push, workflow_dispatch]

jobs:
    c-regression-test:
      # Platform on which this workflow will run
      # ref: https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
      runs-on: ubuntu-latest
      steps:
        - name: Check out this repository
          uses: actions/checkout@v3

        # Steps to be executed in this job
        - name: Build
          run: bash c/build.bash

        - name: Test
          run: ./c/fibonacci_test

    python-regression-test:
      # Platform on which this workflow will run
      # ref: https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
      runs-on: ubuntu-latest
      steps:
        - name: Check out this repository
          uses: actions/checkout@v3

        # Steps to be executed in this job
        - name: Test
          run: python3 python/fibonacci_test.py
